services:
    fastapi:
      image: fastapi:v1
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - 8888:8888

    streamlit:
      image: streamlit:v1
      build:
        context: ./streamlit_app
        dockerfile: Dockerfile
      ports:
        - 8501:8501
      environment:
        API_URL: http://fastapi:8888